---
title: "week2"
author: "Brad McNeney"
date: '2019-01-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 2 exercises for tutorial

1. Predict the outcome of the following:
```
c(1, FALSE)
c("a",1)
c(list(1),"a")
c(TRUE,1)
```

2. If `vv <- list(a=1,b=2)`, why doesn't `as.vector(vv)`
work to coerce `vv` into an atomic vector?

3. What is `dim(cbind(A,A))` if `A = matrix(1:4,2,2)`?

4. What do the following return?
```
TRUE | FALSE
c(TRUE,TRUE) & c(FALSE,TRUE)
c(TRUE,TRUE) && c(FALSE,TRUE)
```

5. Write a code chunk that (i) reads in the 
`gapminder` data from its package, (ii) 
extracts the data on Canada, the United States and
Mexico, and (iii) plots life expectancy 
versus year for these three countries
using different plotting characters for 
each country. Add a `loess` scatterplot
smoother for each country using a span of 3/4.

6. The following code chunk is typed into the R Console.
    - What is the output of the function call `f(5)`?
    - What is the enclosing environment of `f()`?
    - What is the enclosing environment of `g()`?
    - What search order does R use to find the 
    value of `x` when it is needed in `g()`?
```
x <- 1
f <- function(y) {
  g <- function(z) {
    (x+z)^2
  }
  g(y)
}
f(5)
```

